name: 新機能/新要素の提案
title: "【新機能】 <タイトルを入力>"
description: "新しくアイデアがある方はこちら"
#labels: " "
#assignees: " "

body:
- type: markdown
  attributes:
    value: |
      ## タイトル
- type: input
  id: Title
  attributes:
    label: 概要
    description: 実装したいアイデアの概要を記載してください。
- type: textarea
  id: feature
  attributes:
    label: 特徴
    description: 実装したいアイデアの特徴やシナジー、追加することによるメリットを記載してください。
- type: textarea
  id: Description
  attributes:
    label: 説明
    description: 実装したいアイデアの詳細を記載してください。
- type: dropdown
  id: priority
  attributes:
    label: 優先度
    description: この機能の実装優先度を選択してください。
    options:
      - 高(最優先、現在のバージョンで実装)
      - 中(次のバージョン頃で実装予定)
      - 低(完成版近くに実装できていればok)
