name: 新機能/新要素の提案
title: "【新機能/新要素の提案】 <タイトルを入力>"
description: "新しくアイデアがある方はこちら"
#labels: " "
#assignees: " "

body:
- type: markdown
  attributes:
    value: |
      ## タイトル
- type: input
  id: Title
  attributes:
    label: 内容
    description: 実装したいアイデアの内容を書いてください。
- type: textarea
  id: Title
  attributes:
    label: 内容
    description: 実装したいアイデアの特徴やシナジー、追加することによるメリットを書いてください。
- type: textarea
  id: Description
  attributes:
    label: 説明
    description: 実装したいアイデアの詳細を書いてください。
